---
- name: Install the selinux python module
  package: name={{ item }} state=present
  with_items:
    - libselinux-python
    - libsemanage-python
  when: ansible_os_family == "RedHat"

- name: Install the selinux python module
  package: name={{ item }} state=present
  with_items:
    - python-selinux
    - python-semanage
  when: ansible_os_family == "Debian"

- name: Set SELinux boolean to allow nginx to set rlimit
  seboolean: name=httpd_setrlimit state=yes persistent=yes

- name: Set SELinux boolean to allow nginx to proxy on redhat/centos
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  when: ansible_os_family == "RedHat"
